# Generated by Django 4.2.1 on 2023-06-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_desc',
            new_name='event_description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='time_of_creation',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_createdby',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_participant',
        ),
        migrations.DeleteModel(
            name='Eventuser',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(to='events.participant'),
        ),
    ]
