# Generated by Django 4.2.1 on 2023-06-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.AddField(
            model_name='participant',
            name='registered_events',
            field=models.ManyToManyField(related_name='participants', to='events.event'),
        ),
    ]
