# Generated by Django 4.2.1 on 2023-06-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='registered_events',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='registered_events', to='events.participant'),
        ),
    ]
