# Generated by Django 4.2.1 on 2023-06-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_feedback'),
        ('events', '0010_remove_participant_registered_events_and_more'),
    ]

    operations = [
    ]
