# Generated by Django 4.2.1 on 2023-06-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_feedback_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
